### ISSUE TITLE
I can't find the options for the StataLinux package under Preferences > Package Settings 

### ISSUE THREAD

**Issue by avila** [acarril/StataLinux#12]
First of all, thanks for the amazing plugin. Finally sublime text on linux can be comparable to the windows options, when writing stata. 

## description 
![image](https://user-images.githubusercontent.com/31955632/78294761-32876900-752b-11ea-8aff-ad98a2c0ce04.png)

Is it expected to be so?

In my case, I wanted to change the shortcut to run the select lines (or add alternative options such as `F9`).

**Comment by acarril** [comment]
I think I never implemented a menu, because there's so few options I didn't think it was worth it. I'd be happy to accept a pull request if you want to implement it though.

**Comment by avila** [comment]
this issue was fixed in https://github.com/acarril/StataLinux/commit/b77c53bc829d25e2f320992f49d82aea8c05b370.
