### ISSUE TITLE
[Suggestion] Save temp do file in /tmp/ and do not delete it afterwards

### ISSUE THREAD

**Issue by avila** [acarril/StataLinux#15]
## issue 

Currently the do-file is saved in the current working folder and quickly deleted after running. 

## Suggestion

- Save the file in a temporary folder (`/tmp/`)  and do not delete afterwards. 
- The temp file might be overwritten when a new section is send to stata or a filename with a random number could be generated every time. 

## Reasoning 

1) Quite often I run a section of a file or a whole file and find out that, for example, I have another dataset in memory other than the intended one or a variable was already defined. I got used to read the right dataset (or drop the already defined variable) and re-run the temp do-file. 

2) I believe this is the default behaviour in Windows but I don't remember for sure.

**Comment by acarril** [comment]
I agree it sounds better this way. I'll work to implement it soon.

**Comment by avila** [comment]
This was implemented in commit https://github.com/acarril/StataLinux/commit/b77c53bc829d25e2f320992f49d82aea8c05b370.
