### ISSUE TITLE
update package in Package Control

### ISSUE THREAD

**Issue by avila** [acarril/StataLinux#18]
I believe the package in package control is not the latest version as in this repository. Correct? If so, how can one provide the latest version to package control?

**Comment by acarril** [comment]
I'm drafting a new release to update the version in Package Control. It should be ready later today (sorry for the delayed reply).

**Comment by acarril** [comment]
I've released [v1.0.5](https://github.com/acarril/StataLinux/releases/tag/1.0.5) with the latest changes in the repo, which should update the version linked from Package Control (it takes a bit to update). Closing for the moment, but feel free to reopen if there are issues with the release.
