### ISSUE TITLE
Convert legacy syntax definitions

### ISSUE THREAD

**Issue by acarril** [acarril/StataLinux#7]
Currently the syntax is defined via `Stata.tmLanguage` and `Comments.tmPreferences`. According to the PackageDev wiki, [this is outdated](https://github.com/SublimeText/PackageDev/wiki/Legacy-Syntax-Definitions). Apparently it is fairly easy to migrate to the new, preferred format (`.YAML-tmLanguage`) using PackageDev tools.

**Comment by avila** [comment]
there is still some improvement to do on the syntax. I am not very familiar with how sublime works, but I believe one can implement a scope to recognize it is a multi-line command (with `///`) and using this context extract the all lines of the same command (as suggested in issue #11). That would be a nice improvement but the syntax is now already defined in the new yaml format, so I believe this issue could be closed.

**Comment by acarril** [comment]
Oh OK. Maybe expand #11 with that info then. I wouldn't know how to do it though.
